### PR TITLE
Improved docker example

### PR DESCRIPTION
**Pull request by yorammi**
The loading of the docker-compose process, based on work done for Tikal-customer for a live my-bloody-jenkins

### CODE REVIEW

**Comment by odavid** [comment]
Hi @yorammi ,

Have you looked at the [step by step demo folder](https://github.com/odavid/my-bloody-jenkins/tree/master/demo/step-by-step) 
One of the things it deals with is the IP Address issue, using [`host.docker.internal`](https://docs.docker.com/docker-for-mac/networking/#known-limitations-use-cases-and-workarounds) special DNS record instead of trying to find the address by `ifconfig | grep inet...`

**Comment by yorammi** [comment]
Thanks @odavid,
We did wonder (@hagzag as well) how to solve the IP issue for a while.
We'll take a look (I didn't yet) at what you've sent for sure!
Still, I think that the PR is an improvement to the current example (at least as an example of loading a server it few steps only), so I suggest that you'll merge it anyway. WDYT?

**Comment by yorammi** [comment]
@odavid I've added a credential with the GIT_PRIVATE_KEY and it passed the automatic check

**Comment by yorammi** [comment]
Thanks @odavid

**Pull request merged**
