### PR TITLE
Adds support to use OpenID Connect Auth

### PR DESCRIPTION
**Pull request by Reuuke**
Following changes are:
- Adds support to use OpenID Connect to authenticate using self-hosted or public OpenID connect providers.

### CODE REVIEW

**Comment by odavid** [comment]
Hi @Reuuke, 
Thank you for the contribution! 

Can you please add tests for that configuration.
See: https://github.com/odavid/my-bloody-jenkins/blob/master/tests/groovy/config-handlers/SecurityConfigTest.groovy#L20 as an example...

Cheers...

**Comment by Reuuke** [comment]
> For every config, there is a need for automated test.
> See https://github.com/odavid/my-bloody-jenkins/blob/master/tests/groovy/config-handlers/SecurityConfigTest.groovy#L20 as an example

Done :)

**Comment by odavid** [comment]
@Reuuke - did you close this PR on purpose? Just curious...

**Comment by Reuuke** [comment]
> @Reuuke - did you close this PR on purpose? Just curious...

Oops. Misclick

**Comment by odavid** [comment]
@Reuuke - Thank you!
FYI - while guiding you, I missed the part where you need to actually call the test (:
I fixed that here https://github.com/odavid/my-bloody-jenkins/commit/1c1b99ce17081229915e3b42ea5cd44a4dd65fa2#diff-02b70e45ed3c4c71cbc6d5c4b2d26c6dR300 

Will let the CI run and when it passes, will release a version...
Best...

**Pull request merged**
